<a href="https://colab.research.google.com/github/shindeprajakta2711-web/Advanced-DS-codes/blob/main/taxi_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv('ny_taxi_data.csv')

In [2]:
data.head()

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag
0,id2875421,2,14-03-2016 17:24,14-03-2016 17:32,1,-73.982155,40.767937,-73.964630,40.765602,N
1,id2377394,1,12-06-2016 00:43,12-06-2016 00:54,1,-73.980415,40.738564,-73.999481,40.731152,N
2,id3858529,2,19-01-2016 11:35,19-01-2016 12:10,1,-73.979027,40.763939,-74.005333,40.710087,N
3,id3504673,2,06-04-2016 19:32,06-04-2016 19:39,1,-74.010040,40.719971,-74.012268,40.706718,N
4,id2181028,2,26-03-2016 13:30,26-03-2016 13:38,1,-73.973053,40.793209,-73.972923,40.782520,N

In [3]:
data.describe()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
count,16100.000000,16100.000000,16100.000000,16100.000000,16100.000000,16100.000000
mean,1.530435,1.669752,-73.973492,40.751245,-73.972899,40.751890
std,0.499088,1.319063,0.037752,0.027830,0.037529,0.032598
min,1.000000,1.000000,-74.209854,40.604431,-74.379631,40.567341
25%,1.000000,1.000000,-73.991730,40.737755,-73.991249,40.735740
50%,2.000000,1.000000,-73.981781,40.754625,-73.979515,40.754650
75%,2.000000,2.000000,-73.966873,40.768423,-73.962563,40.770210
max,2.000000,6.000000,-73.558289,40.882942,-72.711395,41.311520

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16100 entries, 0 to 16099
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  16100 non-null  object
 1   vendor_id           16100 non-null  int64
 2   pickup_datetime     16100 non-null  object
 3   dropoff_datetime    16100 non-null  object
 4   passenger_count     16100 non-null  int64
 5   pickup_longitude    16100 non-null  float64
 6   pickup_latitude     16100 non-null  float64
 7   dropoff_longitude   16100 non-null  float64
 8   dropoff_latitude    16100 non-null  float64
 9   store_and_fwd_flag  16100 non-null  object
dtypes: float64(4), int64(2), object(4)
memory usage: 1.2+ MB

In [5]:
data.isnull().sum()

id                    0
vendor_id             0
pickup_datetime       0
dropoff_datetime      0
passenger_count       0
pickup_longitude      0
pickup_latitude       0
dropoff_longitude     0
dropoff_latitude      0
store_and_fwd_flag    0
dtype: int64

In [6]:
data['passenger_count'].unique()

array([1, 6, 4, 2, 3, 5])

In [9]:
data['passenger_count'].values
data

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag
0,id2875421,2,14-03-2016 17:24,14-03-2016 17:32,1,-73.982155,40.767937,-73.964630,40.765602,N
1,id2377394,1,12-06-2016 00:43,12-06-2016 00:54,1,-73.980415,40.738564,-73.999481,40.731152,N
2,id3858529,2,19-01-2016 11:35,19-01-2016 12:10,1,-73.979027,40.763939,-74.005333,40.710087,N
3,id3504673,2,06-04-2016 19:32,06-04-2016 19:39,1,-74.010040,40.719971,-74.012268,40.706718,N
4,id2181028,2,26-03-2016 13:30,26-03-2016 13:38,1,-73.973053,40.793209,-73.972923,40.782520,N
...,...,...,...,...,...,...,...,...,...,...
16095,id1197632,1,27-05-2016 09:38,27-05-2016 09:48,1,-73.940025,40.751556,-73.970116,40.754772,N
16096,id3503918,2,07-01-2016 20:42,07-01-2016 20:55,1,-73.963051,40.799149,-73.953934,40.766590,N
16097,id2857349,1,10-01-2016 15:41,10-01-2016 15:47,1,-73.912605,40.774769,-73.922478,40.765701,N
16098,id3803774,1,20-01-2016 16:25,20-01-2016 16:37,1,-73.983444,40.755722,-73.978958,40.782188,N
16099,id0357773,2,07-03-2016 08:06,07-03-2016 08:18,1,-74.000763,40.747421,-73.980850,40.758770,N

In [9]:
'''Create a python program to determine how many captial letterss are in string
Input = Abcd
Output = 1
1. take the input
2. Apply for loop for iteration and to iterate on each letter
3. Check if that letter is capital or not, if capital then it will count or will increase the count
4. These will continue till the loop gets over
5. After completing the loop , it will print the count  '''

In [33]:
input = "AbcD"
count = 0
for i in input:
  if i.isupper():
    count +=1
print(count)

2